### ISSUE TITLE
Return fewer than patchmax_proj_number areas if more cannot be generated

### ISSUE THREAD

**Issue by strangeties** [forsys-sp/forsysr#111]
The number of project areas generated by Patchmax is specified by patchmax_proj_number.

If patchmax_proj_number=3 and only 2 project areas can be generated from the provided stands, Forsys issues a failure.

Instead, we want Forsys to stop and return the 2 generated project areas.

This will help with Planscape productionization (https://github.com/OurPlanscape/Planscape/issues/760).

**Comment by michelledayusfs** [comment]
@strangeties Can you provide an example of this? This was a known issue that I thought was resolved. I just ran forsys with such a situation and it returns the projects it can create when it cannot meet the target number.

**Comment by michelledayusfs** [comment]
I tested it and it is failing again. @codyevers try this script and see if the fix you created earlier only works in the purrr loop.
[Testing_patchmax_inR_viablepatchreturn.txt](https://github.com/forsys-sp/forsysr/files/11127134/Testing_patchmax_inR_viablepatchreturn.txt)

**Comment by strangeties** [comment]
Thanks, Michelle!

In the example I'm running in Planscape, the following combination of parameters works:
```
patchmax_proj_size = 3 
patchmax_proj_size_min = 1
patchmax_proj_number = 3 
```

While the following fails:
```
patchmax_proj_size = 3 
patchmax_proj_size_min = 1
patchmax_proj_number = 5 
```

The failure message is:
`Ill-formed request: Error in search_func(cpp_graph = private$..update_edgelist(), net = private$..update_net(), : No patches possible`

**Comment by michelledayusfs** [comment]
This issue is likely related to issue #106 which was resolved within purrr loop.

**Comment by codyevers** [comment]
There may be two different bugs here. One occurs in the adjust_dist function of patchmax if all stands have already been selected since it is being fed a bunch of blank data frames. This produces a different error message than what @strangeties noted. I'll focus on first, which will hopefully resolve the second.

**Comment by codyevers** [comment]
This should now be fixed. @michelledayusfs or @strangties, can you confirm this works on your end?

**Comment by michelledayusfs** [comment]
I reran the script and ForSys returned the projects it could generate.  Considering this issue resolved.
